 vpc_cidr_blocks = "10.0.0.0/16"
 subnet_cidr_block = "10.0.10.0/24"
 avail_zone = "us-east-2a"
 env_prefix =  "dev"
 my_ip = "0.0.0.0/0"
 instance_type = "t2.micro"
 public_key_location = "C:/Users/abdul/.ssh/id_rsa.pub"
 private_key_location = "C:/Users/abdul/.ssh/id_rsa"
